name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch's name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Node.js for link checker
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check for broken links
        run: |
          # Install broken-link-checker and http-server globally
          npm install -g broken-link-checker http-server

          # Serve the static site in the background
          # Serve from the root directory since it's static files
          http-server . -p 8080 &
          SERVER_PID=$!

          echo "Waiting for server to start..."
          sleep 5 # Give the server some time to start up

          echo "Running link check against the site..."
          # Run the link checker
          # --recursive: Check all links on the served site
          # --ordered: Display links in the order they are found
          # --exclude: Exclude specific domains that might be flaky
          # --filter-level 1: Report only broken links (4xx, 5xx status codes)
          # --timeout: Increase timeout for potentially slow links
          LINK_CHECK_EXIT_CODE=0
          blc http://127.0.0.1:8080 --recursive --ordered --exclude linkedin.com --exclude twitter.com --exclude itch.io --filter-level 1 --timeout 10000 || LINK_CHECK_EXIT_CODE=$?

          # Kill the server
          echo "Killing the server..."
          kill $SERVER_PID

          # Exit with the link checker exit code
          # This ensures the workflow fails if broken links are found
          exit $LINK_CHECK_EXIT_CODE

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository since it's static files
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
